---

- file:
    path: "{{ giscube_fcgis_path }}/{{ giscube_qgisserver_app_path }}"
    state: directory
    owner: "{{ qgisserver_owner }}"
    group: "{{ qgisserver_group }}"
    mode: 0755

# copy fcgi script
- name: copy qgisserver applications to fcgis directory
  template:
        backup=no
        src=data/fcgis/qgisserver/uwsgi_ondemand.ini.j2
        dest={{ giscube_fcgis_path }}/{{ giscube_qgisserver_app_path }}/uwsgi_ondemand.ini
        owner={{ qgisserver_owner }}
        group={{ qgisserver_group }}
        mode=0644

# qgis apt source
- name: APT sources.list file for qgis
  template:
        backup=no
        src=etc/apt/sources.list.d/qgis.list.j2
        dest=/etc/apt/sources.list.d/qgis.list
        owner=root
        group=root
        mode=0644
  register: qgis_sources_list

- name: add qgis key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 51F523511C7028C3
  state: present

# apt-get update
- name: update sources
  apt: update_cache=yes
  when: qgis_sources_list.changed

# apt-get install -y qgis-server
- name: install qgis-server
  apt: name={{ item }} state=latest
  with_items:
    - qgis-server
  tags: packages
