---

- file:
    path: "{{ giscube_fcgis_path }}/{{ giscube_qgisserver_app_path }}"
    state: directory
    owner: "{{ qgisserver_owner }}"
    group: "{{ qgisserver_group }}"
    mode: 0755

# copy fcgi script
- name: copy qgisserver applications to fcgis directory
  template:
        backup=no
        src=data/fcgis/qgisserver/uwsgi_ondemand.ini.j2
        dest={{ giscube_fcgis_path }}/{{ giscube_qgisserver_app_path }}/uwsgi_ondemand.ini
        owner={{ qgisserver_owner }}
        group={{ qgisserver_group }}
        mode=0644

# qgis apt source
- name: APT sources.list file for qgis
  template:
        backup=no
        src=etc/apt/sources.list.d/qgis.list.j2
        dest=/etc/apt/sources.list.d/qgis.list
        owner=root
        group=root
        mode=0644
  when: qgis_apt
  register: qgis_sources_list

# - name: import key for qgis
#   command: gpg --keyserver keyserver.ubuntu.com --recv CAEB3DC3BDF7FB45
#
# - name: add qgis key to apt
#   shell: "gpg --export --armor CAEB3DC3BDF7FB45 | sudo apt-key add -"
#   register: command_result
#   failed_when: "not command_result.stdout == 'OK'"

- name: Add qgis-2017.gpg.key
  apt_key:
    url: https://qgis.org/downloads/qgis-2017.gpg.key
    state: present
  when: qgis_apt
  tags: qgis-key

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: CAEB3DC3BDF7FB45
  when: qgis_apt
  tags: qgis-key

# apt-get update
- name: update sources
  apt: update_cache=yes
  when: qgis_apt
  when: qgis_sources_list.changed

# apt-get install -y qgis-server
- name: install qgis-server
  apt: name={{ item }} state=latest
  with_items:
    - qgis-server
  tags: packages
